spring.application.name=coursesbackend

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/appdbang}
spring.datasource.username=${DB_USER:adminbckang}
spring.datasource.password=${DB_PASSWORD:StrongPassw0rd-2029!}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# JWT Properties
# IMPORTANT: Use a strong, long, and random secret in production.
# You can generate one from a site like https://www.lastpass.com/features/password-generator
jwt.secret=]"*40vas&\r#4}Dp:hlvF_hBUh0abz*L&^Z|'4hgKKsAA~4c/D
jwt.expiration-ms=86400000
# Expiration time in milliseconds (e.g., 86400000ms = 24 hours)
